# Usar la imagen oficial de PostgreSQL basada en Alpine
FROM postgres:alpine

# Establecer variables de entorno (opcional)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=postgres

# Exponer el puerto en el que se ejecuta PostgreSQL
EXPOSE 5432
